[package]
name = "frzr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.26.0"
sha2 = "0.10.2"
hex-literal = "0.3.4"
clap = "3.2.17"
